version: '3.3'
services:
  cache_1:
    image: 'redis:7.0'
    restart: always
    container_name: cache_1
    # build:
    #   context: .
    #   dockerfile: Dockerfile_redis
    environment:
      REDIS_PASSWORD: 'new_password_here'
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/etc/redis/redis.conf
    command: /bin/sh -c "redis-server /etc/redis/redis.conf"
    logging:
      options:
        max-size: 50m